### ISSUE TITLE
新增转发时，连接类型无法保存

### ISSUE THREAD

**Issue by alexjeo** [snltty/p2p-tunnel#1]
取代码编译后，出现如下现象。

新增转发时，连接类型无法保存
![image](https://user-images.githubusercontent.com/42953314/134305091-38115d0b-b0e5-4101-8370-cf43a76d7d72.png)

保存转发后，控制台输出失败
![image](https://user-images.githubusercontent.com/42953314/134305216-8c011ff4-8272-4796-90c1-90f59e886d71.png)

您有其他的联系方式吗？我最近在测试该项目，准备改写linux版本。

**Comment by snltty** [comment]
https://gitee.com/snltty/p2p-tunnel   获取最新版本
