### ISSUE TITLE
啥啥都好，就是打洞失败

### ISSUE THREAD

**Issue by Eglusaxie** [snltty/p2p-tunnel#27]
唉。

**Comment by Eglusaxie** [comment]
打洞失败算issue吗哥哥

**Comment by Eglusaxie** [comment]
防火墙什么是全关了。自己内网的两台机子也能打通。

**Comment by Eglusaxie** [comment]
服了就为了远程连把游戏，折腾一晚上没折腾出来。所有p2p的平台和代理都不行是怎么回事

**Comment by Eglusaxie** [comment]
debug日志没啥看的，就是connect fail
不过这里有另外一个p2p代理工具的提示
![image](https://github.com/snltty/p2p-tunnel/assets/44467205/04ee1159-077e-428e-82eb-83768a4caeb5)

**Comment by Eglusaxie** [comment]
我也进了路由器设置。没看到什么upnp功能。
也不懂这个是什么情况。
是不是说这个什么symmetric nat router，就是搞不了p2p

**Comment by Eglusaxie** [comment]
大概去搜了一下，好像是说对称型nat经常大部分时候就是打不通的。

**Comment by Eglusaxie** [comment]
没事了

**Comment by snltty** [comment]
你这个网络环境估计有点严格，这没办法的
