### ISSUE TITLE
[BUG]tcp 转发时间长了会断开:未选择转发对象，或者未与转发对象建立连接

### ISSUE THREAD

**Issue by chendx-github** [snltty/p2p-tunnel#5]
报错信息
未选择转发对象，或者未与转发对象建立连接

注册服务器代理Tcp转发【WEB 短连接】代理 127.0.0.1:8000 -> 127.0.0.1:80 【DISABLED 插件未 开启】

**Comment by snltty** [comment]
新版本没毛病了
