### ISSUE TITLE
Cant working for UDP Protocol

### ISSUE THREAD

**Issue by BurakIsleyicii** [snltty/p2p-tunnel#9]
Hello, i can working TCP correctly but can not UDP Protocol

**Comment by snltty** [comment]
give me more information

**Comment by BurakIsleyicii** [comment]
I need UDP connection to play CS game but it won't connect. Can you give a demonstration for UDP connection as you did for TCP.

**Comment by snltty** [comment]
your pc connect  127.0.0.1:555 ，send  and receive data。
"send data" will to ”target“ client 127.0.0.1:666。
”receive data“ will from  ”target“ client 127.0.0.1:666。
just like tcp forward
A 127.0.0.1:555 <--> B 127.0.0.1:666
![1](https://user-images.githubusercontent.com/10977033/187693479-de7b2b69-7327-4809-b98a-38dd86e7be4b.png)

**Comment by BurakIsleyicii** [comment]
That's how I did it already, but it can't connect. It does not give an error, but it does not connect.

**Comment by snltty** [comment]
see home page，B client conected tunnel
if udp   "communication channel"  choice  只udp
if tcp   "communication channel"  choice  只tcp

**Comment by ShiftyTR** [comment]
I tried it with counter strike 1.6 and udp not working 

> That's how I did it already, but it can't connect. It does not give an error, but it does not connect.

He is right

**Comment by ShiftyTR** [comment]
Yes I did like this maybe mtu problem. I dont know udp not working

**Comment by snltty** [comment]
cs1.6 [https://www.bilibili.com/video/BV1hB4y1n738/](https://gitee.com/link?target=https%3A%2F%2Fwww.bilibili.com%2Fvideo%2FBV1hB4y1n738%2F)
